name: valuepm
favicon: null
layout_spectrum: 0.006803282769396901
typography_spectrum: 0.3219506782479584
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f9f9f9'
    - '#d0c5ba'
    - '#9fa3ba'
    - '#926552'
    - '#191111'
  brandStrength: 0.5
  lightness: 0.875
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
